apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/KonstantinPetkov96/flux-gitops.git
  ref:
    branch: main
