apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.32
      sourceRef:
        kind: HelmRepository
        name: weave-gitops-helm
        namespace: flux-system
  values:
    adminUser:
      create: true 
      username: admin
      passwordHash: "$2y$05$D5iE2fRQicaGSt9H5SJfb.bPTBEyqzWiWnYKVLilYSvAFHm61cq8u"