apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: guestbook-prod
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/prod
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-repo
  targetNamespace: flux-system
