apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: guestbook-pr
  namespace: flux-system
spec:
  interval: 1m
  timeout: 2m
  targetNamespace: guestbook-prod
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/helm-guestbook
      sourceRef:
        kind: GitRepository
        name: flux-repo
      version: "0.1.2"
      reconcileStrategy: Revision
      valuesFiles:
        - charts/helm-guestbook/values.yaml
        - charts/helm-guestbook/values-prod.yaml   