apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: guestbook-qa
  namespace: flux-system
spec:
  interval: 1m
  timeout: 2m
  targetNamespace: guestbook-qa
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/helm-guestbook
      sourceRef:
        kind: GitRepository
        name: flux-repo
      version: "*"
      reconcileStrategy: Revision
      valuesFiles:
        - values.yaml
        - values-qa.yaml     
